# .github/workflows/build-mkdocs-folders.yml

name: Build all MkDocs projects into /docs

on:
  push:
    branches:
      - gh-pages  # <<< NUR bei Push/Merge auf gh-pages Branch

permissions:
  contents: read
  actions: write

jobs:
  build-all-mkdocs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.8
        uses: actions/setup-python@v5
        with:
          python-version: '3.8'

      - name: Install MkDocs
        run: pip install mkdocs

      - name: Build all MkDocs projects
        run: |
          mkdir -p docs
          
          # Suche alle Ordner mit einer mkdocs.yml
          for mkdocs_file in $(find . -name "mkdocs.yml"); do
            dir=$(dirname "$mkdocs_file")
            name=$(basename "$dir")
            
            echo "Building MkDocs project in $dir..."

            mkdocs build --clean --site-dir "../docs/$name" -f "$mkdocs_file"
          done
          
      - name: Commit and push docs folder
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          git add docs
          
          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git commit -m "Update built MkDocs documentation"
            git push origin gh-pages
          fi
